### ISSUE TITLE
KnightLauncher fails to launch on Windows due to installation error, suggest clarifying README.md

### ISSUE THREAD

**Issue by Peliex** [lucasluqui/KnightLauncher#41]
Precompiled logfile after trying to execute
```
2023/08/17 16:36:39:622 INFO com.lucasallegri.launcher: ------------ VM Info ------------
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: OS Name: Windows 10
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: OS Arch: amd64
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: OS Vers: 10.0
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: Java Home: C:\Program Files\Zulu\zulu-17
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: Java Vers: 17.0.8
2023/08/17 16:36:39:628 INFO com.lucasallegri.launcher: User Name: trint
2023/08/17 16:36:39:629 INFO com.lucasallegri.launcher: User Home: C:\Users\trint
2023/08/17 16:36:39:629 INFO com.lucasallegri.launcher: Current Directory: C:\Users\trint\Downloads\KnightLauncher-1.7.3
2023/08/17 16:36:39:629 INFO com.lucasallegri.launcher: ---------------------------------
2023/08/17 16:36:41:232 WARNING WindowsPreferences.<init>: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0xffffffff80000002. Windows RegCreateKeyEx(...) returned error code 5.
java.lang.NoSuchMethodException: java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int,[B,int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
	at com.lucasallegri.util.WinRegistry.<clinit>(WinRegistry.java:51)
	at com.lucasallegri.util.SteamUtil.getGamePathWindows(SteamUtil.java:20)
	at com.lucasallegri.launcher.LauncherApp.checkStartLocation(LauncherApp.java:137)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:58)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.lucasallegri.util.WinRegistry.regOpenKey" is null
	at com.lucasallegri.util.WinRegistry.readString(WinRegistry.java:285)
	at com.lucasallegri.util.WinRegistry.readString(WinRegistry.java:99)
	at com.lucasallegri.util.SteamUtil.getGamePathWindows(SteamUtil.java:20)
	at com.lucasallegri.launcher.LauncherApp.checkStartLocation(LauncherApp.java:137)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:58)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
```

I've since moved to trying to compile the source but the output jarfile from Maven after resolving dependencies will not output anything other than the popup window declaring that the installation is improper.

**Comment by Peliex** [comment]
Moving the file to the Spiral Knights directory allows the jarfile to open.

**Comment by lucasluqui** [comment]
Will clarify this, thank you.
