### ISSUE TITLE
Cannot compile on Windows, even with resolved dependency errors.

### ISSUE THREAD

**Issue by Peliex** [lucasluqui/KnightLauncher#42]
Resolved pom.xml dependency errors as outlined in this commit: https://github.com/Peliex/KnightLauncher/commit/0a7402081fc266c30f289feb1b5060c5070eb6e4

Jarfile compiles, moving to Spiral Knights Directory results in the following output: [old-knightlauncher.log](https://github.com/lucasluqui/KnightLauncher/files/12374399/old-knightlauncher.log)

```
2023/08/17 17:51:20:473 INFO com.lucasallegri.launcher: ------------ VM Info ------------
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: OS Name: Windows 10
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: OS Arch: amd64
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: OS Vers: 10.0
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: Java Home: C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot\jre
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: Java Vers: 1.8.0_382
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: User Name: trint
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: User Home: C:\Users\trint
2023/08/17 17:51:20:477 INFO com.lucasallegri.launcher: Current Directory: W:\SteamLibrary\steamapps\common\Spiral Knights
2023/08/17 17:51:20:482 INFO com.lucasallegri.launcher: ---------------------------------
2023/08/17 17:51:20:490 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:80)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:491 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:81)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:491 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:82)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:491 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:83)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:84)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:85)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:86)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:87)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:88)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:492 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:89)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:493 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:90)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
2023/08/17 17:51:20:493 SEVERE com.lucasallegri.launcher.settings: java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
java.io.FileNotFoundException: W:\SteamLibrary\steamapps\common\Spiral Knights\KnightLauncher.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.lucasallegri.launcher.settings.SettingsProperties.getValue(SettingsProperties.java:43)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:91)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.lucasallegri.launcher.settings.SettingsProperties.load(SettingsProperties.java:91)
	at com.lucasallegri.launcher.settings.SettingsProperties.setup(SettingsProperties.java:37)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:60)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
```

**Comment by lucasluqui** [comment]
Greetings.

The dependencies that were missing to compile should be in the lib/ directory, no need to reference them through Maven (there's some libraries that need to be on a specific release candidate version for compatibility purposes). Putting that aside I see you were able to compile after all, which is good.

I'm uncertain why it would fail to open the KnightLauncher.properties file, this used to be a common error back in KL's early development but fixed over the years. Perhaps it's lacking permissions within that directory? Might not have been created at all? I certainly cannot assess just from the logging output. It's really odd.

Please let me know if there's any advance on this, I'll give it a look myself too.
