### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by SirDank** [lucasluqui/KnightLauncher#45]
Spiral Knights runs on RPi4

KnightLauncher does not!

Log:

```
2023/11/17 16:36:17:378 INFO com.lucasallegri.launcher: ------------ VM Info ------------
2023/11/17 16:36:17:389 INFO com.lucasallegri.launcher: OS Name: Linux
2023/11/17 16:36:17:390 INFO com.lucasallegri.launcher: OS Arch: aarch64
2023/11/17 16:36:17:390 INFO com.lucasallegri.launcher: OS Vers: 6.1.21-v8+
2023/11/17 16:36:17:391 INFO com.lucasallegri.launcher: Java Home: /usr/lib/jvm/temurin-8-jre-arm64
2023/11/17 16:36:17:392 INFO com.lucasallegri.launcher: Java Vers: 1.8.0_392
2023/11/17 16:36:17:392 INFO com.lucasallegri.launcher: User Name: sirdank
2023/11/17 16:36:17:393 INFO com.lucasallegri.launcher: User Home: /home/sirdank
2023/11/17 16:36:17:393 INFO com.lucasallegri.launcher: Current Directory: /home/sirdank/Desktop/spiral
2023/11/17 16:36:17:394 INFO com.lucasallegri.launcher: ---------------------------------
.
.
.
2023/11/17 16:36:17:440 INFO com.lucasallegri.launcher.settings: Successfully loaded all settings from prop file.
96
96
96
96
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/sirdank/.discord-rpc/libdiscord-rpc.so: /home/sirdank/.discord-rpc/libdiscord-rpc.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1100)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.lucasallegri.discord.DiscordRPC.start(DiscordRPC.java:32)
	at com.lucasallegri.launcher.LauncherApp.<init>(LauncherApp.java:64)
	at com.lucasallegri.launcher.LauncherApp.main(LauncherApp.java:41)
```

**Comment by lucasluqui** [comment]
There's no arm binaries for discord's rpc module, I have already tried getting sk to work on a rpi (3b+) in the past but no to avail, there's a few other libraries the game uses that are not compiled for arm.

I am not sure what wizardry happens on either the rpi4 or raspios that allows it to run now and it's not in my plans to ditch rpc for arm support.

If you really want to give it a try there's one really old knight launcher version that had arm support but I cannot guarantee it'll work
https://github.com/lucasluqui/KnightLauncher/releases/tag/1.2.9

**Comment by 1ynxy** [comment]
Given the increase an available higher-powered ARM devices (Snapdragon X, etc) which don't have the discord-rpc lib available (which appears to have actually been deprecated entirely?), any chance of this modification making it into a future release?

Thanks.

**Comment by lucasluqui** [comment]
From Knight Launcher 2.0 onward the issue mentioned in this issue should no longer be present. I don't have an ARM device to test on, let me know if this is still occurring.

**Comment by 1ynxy** [comment]
I'm currently running on a Snapdragon X Elite device under Ubuntu 24.10 Concept release- and the issue appears to still occurs.

> libdiscord-rpc.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)

If I can help debug this in any way, I'd love to.

**Comment by lucasluqui** [comment]
Let me take a look at your knightlauncher.log file, assuming it manages to generate one

**Comment by 1ynxy** [comment]
Sure thing, I've attached it below-

[knightlauncher.log](https://github.com/user-attachments/files/18118043/knightlauncher.log)

**Comment by Crowfunder** [comment]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/user/.discord-rpc/libdiscord-rpc.so: /home/user/.discord-rpc/libdiscord-rpc.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2402)
	at java.base/java.lang.Runtime.load0(Runtime.java:858)
	at java.base/java.lang.System.load(System.java:2035)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.luuqui.discord.DiscordRPC.start(DiscordRPC.java:32)
	at com.luuqui.launcher.LauncherApp.<init>(LauncherApp.java:84)
	at com.luuqui.launcher.LauncherApp.main(LauncherApp.java:54)
```
As per [this issue](https://github.com/KRTirtho/spotube/issues/1649) I believe it may be necessary to compile [libdiscord-rpc.so](https://github.com/discord/discord-rpc) from source to get it work natively on ARM based machines. Try compiling it on your machine and substituting the file mentioned in the traceback.

**Comment by 1ynxy** [comment]
Ah, it appears there is currently an arm64 binary for libdiscord-rpc on apt, and while installing it doesn't fix the problem because KnightLauncher is searching for it in ~/.discord-rpc/, a symlink to where it is installed (/usr/lib/aarch64-linux-gnu/libdiscord-rpc.so) will allow me to launch KnightLauncher without issue.

Still, is it possible to make this requirement optional at all? I really don't care for Discord as a platform, nor for Discord RPC integration.

**Comment by 1ynxy** [comment]
Of course, I can email you or whatever is easier for you.

**Comment by SirDank** [comment]
woah, @lucasluqui you can send it to me as well, dm me on discord
