### ISSUE TITLE
KnightLauncher does not allow JVM patching of the Steam version under Linux

### ISSUE THREAD

**Issue by DeinAlptraum** [lucasluqui/KnightLauncher#46]
SpiralKnights can be run non-natively on Linux by changing the Steam settings: "Settings" -> "Compatibility" -> "Enable Steam Play for all other titles". This runs very well from my experience so far.
This runs Spiral Knights' Windows version through Steam's Proton compatibility layer. The game files are thus exactly the same and I was able to 64-bit patch the game by simply replacing the `java_vm` folder in the game files with the extracts of https://lucasallegri.b-cdn.net/knightlauncher/v2/java/windows/7u80/redist.zip. This has been running great without any trouble so far.

I would suggest changing [LauncherApp.java line 226-227](https://github.com/lucasluqui/KnightLauncher/blob/efab12d33482c866d386630b789d3416759f7055/src/main/java/com/lucasallegri/launcher/LauncherApp.java#L226C1-L227C46):
```java
    // Currently Java VM patching is only supported on Windows systems.
    if(!SystemUtil.isWindows()) return false;
```
to 
```java
    // Currently Java VM patching is only supported on Windows systems and Linux installs through Steam.
    if(!SystemUtil.isWindows() && !(SystemUtil.isUnix() && Settings.gamePlatform.startsWith("Steam"))) return false;
```
to allow JVM patching on both Windows and Linux+Steam.

(sorry for no PR, I couldn't get KL to compile and I don't like to submit code I didn't test)

**Comment by DeinAlptraum** [comment]
I had only tested with 7u80 so far, and it seems that there's some trouble with `8u202` & `8u251`: the game crashes with the following error in projectx.log
```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.lucasallegri.bootstrap.ProjectXBootstrap.main(ProjectXBootstrap.java:78)
Caused by: java.lang.ExceptionInInitializerError
	at javax.crypto.Cipher.getInstance(Cipher.java:518)
	at com.threerings.presents.b.d.a(SourceFile:89)
	at com.threerings.presents.b.d.a(SourceFile:202)
	at com.threerings.presents.client.Client.bG(SourceFile:236)
	at com.threerings.projectx.client.ProjectXApp.<init>(SourceFile:378)
	... 5 more
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:93)
	... 10 more
Caused by: java.lang.SecurityException: The jurisdiction policy files are not signed by the expected signer! (Policy files are specific per major JDK release.Ensure the correct version is installed.)
	at javax.crypto.JarVerifier.verifyPolicySigned(JarVerifier.java:328)
	at javax.crypto.JceSecurity.loadPolicies(JceSecurity.java:378)
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:323)
	at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
	at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
	... 10 more
```
After uncommenting the line `crypto.policy=unlimited` on line 829 in `java_vm/lib/security/java.security`, I was able to start the game normally, for both `8u202` and `8u251`
(I tested all of this with a fresh install of SK every time)

**Comment by lucasluqui** [comment]
All Java VMs on KL's CDN have been updated to contain this patch, it might take a few hours until the cached versions are updated.
